### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by as4456** [adamancer/pyncei#1]
Hi,

I just tried the examples provided but they are returning empty list.

Thanks

**Comment by adamancer** [comment]
It looks like the NCEI endpoint isn’t playing well with encoded URLs. I added an encode_queries attribute to the NCEIReader object. Try seeing if the examples work with that attribute set to False.

Adam

**Comment by as4456** [comment]
Hi Adam,
Thanks for the update. It works now. 

One thing I wanted to ask you was that get_data currently pulls records for one year at a time. Is this a constraint from the NCEI side or is it for some other reason.

Thanks,
Aman

**Comment by adamancer** [comment]
That constraint is set by NCEI (see startdate/enddate at https://www.ncdc.noaa.gov/cdo-web/webservices/v2#data).

Adam

**Comment by as4456** [comment]
Thanks for clearing this.

Regards,
Aman
