### ISSUE TITLE
Max_Temp looks incorrect

### ISSUE THREAD

**Issue by as4456** [adamancer/pyncei#2]
Hi Adam,
For certain stations, the data(TMAX) seems incorrect. When I view the data for a specific year for these particular stations using the web tool, I get different data .

For e.g. for the station, RIVERSIDE FIRE STATION 3, CA US (GHCND:USC00047470), I am getting
TMAX in range of 200, which seems incorrect. I get different results when queried from web
(https://www.ncdc.noaa.gov/cdo-web/datasets/GHCND/stations/GHCND:USC00047470/detail).

#Example 
from datetime import date
from pyncei.reader import NCEIReader
import datetime as dt
import csv
import pandas as pd

token = '##############'
ncei = NCEIReader(token,encode_queries=False)
mindate = '1970-01-01'  # either yyyy-mm-dd or a datetime object
maxdate = dt.datetime.today().strftime("%Y-%m-%d")
datatypes = ['TMAX']
dataset = 'GHCND'
minyear = int(mindate[:4])
year = date.today().year
val='GHCND:USC00047470'
ncei.get_data(dataset=dataset,
                                        station=val,
                                        datatype=datatypes,
                                        startdate=date(1990, 1, 1),
                                        enddate=date(1990, 12, 31))

There are several other stations for which the data seems incorrect.

Thanks

**Comment by as4456** [comment]
Hi Adam,
Could you kindly tell what could be the reason for this difference.

Thanks

**Comment by adamancer** [comment]
This has to do with the how the NCEI data endpoint returns data if no units keyword is specified. I’ve added that keyword to the get_data() method. It accepts either ‘standard’ or ‘metric’. I think that should solve your issue, but let me know if not.

Thanks!
Adam

**Comment by as4456** [comment]
Hi Adam,
It works now.

Thanks
